name: Lint

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  linting:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.x # Run with latest stable Deno.

      - name: Check format
        run: deno fmt --check

      - name: Run Linter
        run: deno lint